//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSDES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAM_BOOKING
    {
        public int Steb { get; set; }
        public string EXAM_MODULE_NAME { get; set; }
        public string EXAM_NUMBER { get; set; }
        public System.DateTime EXAM_DATE { get; set; }
        public System.TimeSpan EXAM_TIME { get; set; }
        public int Stid { get; set; }
    
        public virtual STUDENT_INFO STUDENT_INFO { get; set; }
    }
}
