//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSDES.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class STUDENTWAREHOUSEEntities : DbContext
    {
        public STUDENTWAREHOUSEEntities()
            : base("name=STUDENTWAREHOUSEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMINS { get; set; }
        public virtual DbSet<EXAM_BOOKING> EXAM_BOOKING { get; set; }
        public virtual DbSet<STUDENT_EXAM_RESULTS> STUDENT_EXAM_RESULTS { get; set; }
        public virtual DbSet<STUDENT_INFO> STUDENT_INFO { get; set; }
        public virtual DbSet<STUDENT_PROJECT_RESULTS> STUDENT_PROJECT_RESULTS { get; set; }
        public virtual DbSet<STUDENT_TEST_RESULTS> STUDENT_TEST_RESULTS { get; set; }
    }
}
