//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSDES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_INFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENT_INFO()
        {
            this.EXAM_BOOKING = new HashSet<EXAM_BOOKING>();
            this.STUDENT_EXAM_RESULTS = new HashSet<STUDENT_EXAM_RESULTS>();
            this.STUDENT_PROJECT_RESULTS = new HashSet<STUDENT_PROJECT_RESULTS>();
            this.STUDENT_TEST_RESULTS = new HashSet<STUDENT_TEST_RESULTS>();
        }
    
        public int Stid { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string GENDER { get; set; }
        public int AGE { get; set; }
        public System.DateTime ADMISSION_DATE { get; set; }
        public string COURSE_NAME { get; set; }
        public int COURSE_DURATION { get; set; }
        public string COURSE_TRAINER { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string CONTACT_NUMBER { get; set; }
        public Nullable<int> YEAR_IN_COLLEGE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXAM_BOOKING> EXAM_BOOKING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_EXAM_RESULTS> STUDENT_EXAM_RESULTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_PROJECT_RESULTS> STUDENT_PROJECT_RESULTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_TEST_RESULTS> STUDENT_TEST_RESULTS { get; set; }
    }
}
